### ISSUE TITLE
Add eslint base rules to new projects

### ISSUE THREAD

**Issue by rglover** [cheatcode/joystick#228]
Would like to have this so we can handle linting of code for undefined variables.

**Comment by rglover** [comment]
This should be conditional in the CLI.

**Comment by rglover** [comment]
This should be a very simple, easy to delete thing like this:

```yaml
extends:
  - eslint:recommended
parser: "@babel/eslint-parser"
```

Just add an `.eslintrc.yaml` file to the root and be done with it. That can be customized or deleted per the developer's wishes.
